### ISSUE TITLE
Inner Product Demo Doesn't Work

### ISSUE THREAD

**Issue by seanmrandall** [fionser/RLWE#1]
Running the demo does not give me valid answersr for the inner product (should be 5,0,5). Results vary every time I run the demo; results are either the correct answer or one higher. 

My last four runs;
6
0
6

6
0
5

6
1
5

5
0
6

**Comment by fionser** [comment]
I am sorry that this very naive implementation of RLWE is not used anymore. 
I strongly recommend you to have a look at HElib. Thank you for you concerns.
